from ...protocol import *
import sublime
from _typeshed import Incomplete
from typing import Any, Callable, Generic, TypeVar, TypedDict
from typing_extensions import NotRequired

INT_MAX: Incomplete
UINT_MAX = INT_MAX
P = TypeVar('P', bound=LSPAny)
R = TypeVar('R', bound=LSPAny)

class RequestMessage(TypedDict):
    jsonrpc: str
    id: str | int
    method: str
    params: NotRequired[Any]

class ResponseMessage(TypedDict):
    jsonrpc: str
    id: str | int
    result: NotRequired[Any]
    error: NotRequired[ResponseError]

class NotificationMessage(TypedDict):
    jsonrpc: str
    method: str
    params: NotRequired[Any]
JSONRPCMessage = RequestMessage | ResponseMessage | NotificationMessage

class Request(Generic[P, R]):
    __slots__: Incomplete
    method: Incomplete
    params: Incomplete
    view: Incomplete
    progress: Incomplete
    on_partial_result: Incomplete
    def __init__(self, method: str, params: P = None, view: sublime.View | None = None, progress: bool = False, on_partial_result: Callable[[R], None] | None = None) -> None: ...
    @classmethod
    def initialize(cls, params: InitializeParams) -> Request[InitializeParams, InitializeResult]: ...
    @classmethod
    def complete(cls, params: CompletionParams, view: sublime.View) -> Request[CompletionParams, list[CompletionItem] | CompletionList | None]: ...
    @classmethod
    def signatureHelp(cls, params: SignatureHelpParams, view: sublime.View) -> Request[SignatureHelpParams, SignatureHelp | None]: ...
    @classmethod
    def codeAction(cls, params: CodeActionParams, view: sublime.View) -> Request[CodeActionParams, list[Command | CodeAction] | None]: ...
    @classmethod
    def documentColor(cls, params: DocumentColorParams, view: sublime.View) -> Request[DocumentColorParams, list[ColorInformation]]: ...
    @classmethod
    def colorPresentation(cls, params: ColorPresentationParams, view: sublime.View) -> Request[ColorPresentationParams, list[ColorPresentation]]: ...
    @classmethod
    def executeCommand(cls, params: ExecuteCommandParams, *, progress: bool = False) -> Request[ExecuteCommandParams, R]: ...
    @classmethod
    def willSaveWaitUntil(cls, params: WillSaveTextDocumentParams, view: sublime.View) -> Request[WillSaveTextDocumentParams, list[TextEdit] | None]: ...
    @classmethod
    def willRenameFiles(cls, params: RenameFilesParams) -> Request[RenameFilesParams, WorkspaceEdit | None]: ...
    @classmethod
    def documentSymbols(cls, params: DocumentSymbolParams, view: sublime.View) -> Request[DocumentSymbolParams, list[DocumentSymbol] | list[SymbolInformation] | None]: ...
    @classmethod
    def documentHighlight(cls, params: DocumentHighlightParams, view: sublime.View) -> Request[DocumentHighlightParams, list[DocumentHighlight] | None]: ...
    @classmethod
    def documentLink(cls, params: DocumentLinkParams, view: sublime.View) -> Request[DocumentLinkParams, list[DocumentLink]]: ...
    @classmethod
    def semanticTokensFull(cls, params: SemanticTokensParams, view: sublime.View) -> Request[SemanticTokensParams, SemanticTokens | None]: ...
    @classmethod
    def semanticTokensFullDelta(cls, params: SemanticTokensDeltaParams, view: sublime.View) -> Request[SemanticTokensDeltaParams, SemanticTokens | SemanticTokensDelta | None]: ...
    @classmethod
    def semanticTokensRange(cls, params: SemanticTokensRangeParams, view: sublime.View) -> Request[SemanticTokensRangeParams, SemanticTokens | None]: ...
    @classmethod
    def prepareCallHierarchy(cls, params: CallHierarchyPrepareParams, view: sublime.View) -> Request[CallHierarchyPrepareParams, list[CallHierarchyItem] | None]: ...
    @classmethod
    def incomingCalls(cls, params: CallHierarchyIncomingCallsParams) -> Request[CallHierarchyIncomingCallsParams, list[CallHierarchyIncomingCall] | None]: ...
    @classmethod
    def outgoingCalls(cls, params: CallHierarchyOutgoingCallsParams) -> Request[CallHierarchyOutgoingCallsParams, list[CallHierarchyOutgoingCall] | None]: ...
    @classmethod
    def prepareTypeHierarchy(cls, params: TypeHierarchyPrepareParams, view: sublime.View) -> Request[TypeHierarchyPrepareParams, list[TypeHierarchyItem] | None]: ...
    @classmethod
    def supertypes(cls, params: TypeHierarchySupertypesParams) -> Request[TypeHierarchySupertypesParams, list[TypeHierarchyItem] | None]: ...
    @classmethod
    def subtypes(cls, params: TypeHierarchySubtypesParams) -> Request[TypeHierarchySubtypesParams, list[TypeHierarchyItem] | None]: ...
    @classmethod
    def resolveCompletionItem(cls, params: CompletionItem, view: sublime.View) -> Request[CompletionItem, CompletionItem]: ...
    @classmethod
    def resolveDocumentLink(cls, params: DocumentLink, view: sublime.View) -> Request[DocumentLink, DocumentLink]: ...
    @classmethod
    def inlayHint(cls, params: InlayHintParams, view: sublime.View) -> Request[InlayHintParams, list[InlayHint] | None]: ...
    @classmethod
    def resolveInlayHint(cls, params: InlayHint, view: sublime.View) -> Request[InlayHint, InlayHint]: ...
    @classmethod
    def rename(cls, params: RenameParams, view: sublime.View, *, progress: bool = False) -> Request[RenameParams, WorkspaceEdit | None]: ...
    @classmethod
    def prepareRename(cls, params: PrepareRenameParams, view: sublime.View, progress: bool = False) -> Request[PrepareRenameParams, PrepareRenameResult | None]: ...
    @classmethod
    def selectionRange(cls, params: SelectionRangeParams) -> Request[SelectionRangeParams, list[SelectionRange] | None]: ...
    @classmethod
    def foldingRange(cls, params: FoldingRangeParams, view: sublime.View) -> Request[FoldingRangeParams, list[FoldingRange] | None]: ...
    @classmethod
    def formatting(cls, params: DocumentFormattingParams, view: sublime.View) -> Request[DocumentFormattingParams, list[TextEdit] | None]: ...
    @classmethod
    def range_formatting(cls, params: DocumentRangeFormattingParams, view: sublime.View) -> Request[DocumentRangeFormattingParams, list[TextEdit] | None]: ...
    @classmethod
    def ranges_formatting(cls, params: DocumentRangesFormattingParams, view: sublime.View) -> Request[DocumentRangesFormattingParams, list[TextEdit] | None]: ...
    @classmethod
    def workspaceSymbol(cls, params: WorkspaceSymbolParams) -> Request[WorkspaceSymbolParams, list[SymbolInformation] | list[WorkspaceSymbol] | None]: ...
    @classmethod
    def resolveWorkspaceSymbol(cls, params: WorkspaceSymbol) -> Request[WorkspaceSymbol, WorkspaceSymbol]: ...
    @classmethod
    def documentDiagnostic(cls, params: DocumentDiagnosticParams, view: sublime.View) -> Request[DocumentDiagnosticParams, DocumentDiagnosticReport]: ...
    @classmethod
    def workspaceDiagnostic(cls, params: WorkspaceDiagnosticParams, on_partial_result: Callable[[WorkspaceDiagnosticReport], None]) -> Request[WorkspaceDiagnosticParams, WorkspaceDiagnosticReport]: ...
    @classmethod
    def shutdown(cls) -> Request[None, None]: ...
    def __repr__(self) -> str: ...
    def to_payload(self, request_id: int) -> RequestMessage: ...

class Error(Exception):
    code: Incomplete
    data: Incomplete
    def __init__(self, code: int, message: str, data: Any = None) -> None: ...
    @classmethod
    def from_lsp(cls, params: ResponseError) -> Error: ...
    def to_lsp(self) -> ResponseError: ...
    def __str__(self) -> str: ...
    @classmethod
    def from_exception(cls, ex: Exception) -> Error: ...

class Response(Generic[P]):
    __slots__: Incomplete
    request_id: Incomplete
    result: Incomplete
    def __init__(self, request_id: str | int, result: P) -> None: ...
    def to_payload(self) -> ResponseMessage: ...

class Notification(Generic[P]):
    __slots__: Incomplete
    method: Incomplete
    params: Incomplete
    def __init__(self, method: str, params: P = None) -> None: ...
    @classmethod
    def initialized(cls) -> Notification[InitializedParams]: ...
    @classmethod
    def didOpen(cls, params: DidOpenTextDocumentParams) -> Notification[DidOpenTextDocumentParams]: ...
    @classmethod
    def didChange(cls, params: DidChangeTextDocumentParams) -> Notification[DidChangeTextDocumentParams]: ...
    @classmethod
    def willSave(cls, params: WillSaveTextDocumentParams) -> Notification[WillSaveTextDocumentParams]: ...
    @classmethod
    def didSave(cls, params: DidSaveTextDocumentParams) -> Notification[DidSaveTextDocumentParams]: ...
    @classmethod
    def didClose(cls, params: DidCloseTextDocumentParams) -> Notification[DidCloseTextDocumentParams]: ...
    @classmethod
    def didRenameFiles(cls, params: RenameFilesParams) -> Notification[RenameFilesParams]: ...
    @classmethod
    def didChangeConfiguration(cls, params: DidChangeConfigurationParams) -> Notification[DidChangeConfigurationParams]: ...
    @classmethod
    def didChangeWatchedFiles(cls, params: DidChangeWatchedFilesParams) -> Notification[DidChangeWatchedFilesParams]: ...
    @classmethod
    def didChangeWorkspaceFolders(cls, params: DidChangeWorkspaceFoldersParams) -> Notification[DidChangeWorkspaceFoldersParams]: ...
    @classmethod
    def exit(cls) -> Notification[None]: ...
    def __repr__(self) -> str: ...
    def to_payload(self) -> NotificationMessage: ...

class Point:
    row: Incomplete
    col: Incomplete
    def __init__(self, row: int, col: int) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    @classmethod
    def from_lsp(cls, point: Position) -> Point: ...
    def to_lsp(self) -> Position: ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __le__(self, other): ...

class ResponseError(TypedDict):
    code: int
    message: str
    data: NotRequired[LSPAny]

class ResolvedCodeLens(TypedDict):
    range: Range
    command: Command
    uses_cached_command: NotRequired[bool]
RangeLsp = Range
