import sublime
from ..protocol import CodeLens as CodeLens, Command as Command, Range as Range
from .core.constants import CODE_LENS_ENABLED_KEY as CODE_LENS_ENABLED_KEY
from .core.protocol import Error as Error, ResolvedCodeLens as ResolvedCodeLens
from .core.registry import LspTextCommand as LspTextCommand, LspWindowCommand as LspWindowCommand, windows as windows
from .core.views import range_to_region as range_to_region
from _typeshed import Incomplete
from typing_extensions import TypeGuard

def is_resolved(code_lens: CodeLens | ResolvedCodeLens) -> TypeGuard[ResolvedCodeLens]: ...

class HashableRange:
    data: Incomplete
    def __init__(self, r: Range, /) -> None: ...
    def __hash__(self): ...
    def __eq__(self, rhs: object) -> bool: ...
    def __lt__(self, rhs: HashableRange) -> bool: ...

class CachedCodeLens:
    __slots__: Incomplete
    data: Incomplete
    range: Incomplete
    cached_command: Incomplete
    def __init__(self, data: CodeLens) -> None: ...
    def on_resolve(self, response: CodeLens | Error) -> None: ...

class CodeLensCache:
    code_lenses: Incomplete
    def __init__(self) -> None: ...
    def handle_response_async(self, code_lenses: list[CodeLens]) -> None: ...
    def unresolved_visible_code_lenses(self, view: sublime.View) -> list[CachedCodeLens]: ...
    def code_lenses_with_command(self) -> list[ResolvedCodeLens]:
        """ Returns only the code lenses that are either resolved, or have a cached command. """

class LspToggleCodeLensesCommand(LspWindowCommand):
    capability: str
    @classmethod
    def are_enabled(cls, window: sublime.Window | None) -> bool: ...
    def is_checked(self) -> bool: ...
    def run(self) -> None: ...
    def _update_views_async(self, enable: bool) -> None: ...

class LspCodeLensCommand(LspTextCommand):
    capability: str
    def run(self, edit: sublime.Edit) -> None: ...
    def want_event(self) -> bool: ...
    def on_select(self, commands: list[tuple[str, Command]], index: int) -> None: ...
