import sublime
import sublime_plugin
from ..protocol import Diagnostic as Diagnostic, DocumentUri as DocumentUri, Location as Location, LocationLink as LocationLink
from .core.constants import DIAGNOSTIC_KINDS as DIAGNOSTIC_KINDS
from .core.input_handlers import PreselectedListInputHandler as PreselectedListInputHandler
from .core.paths import simple_project_path as simple_project_path
from .core.protocol import Point as Point, Request as Request
from .core.registry import LspTextCommand as LspTextCommand, LspWindowCommand as LspWindowCommand, get_position as get_position
from .core.sessions import Session as Session
from .core.settings import userprefs as userprefs
from .core.types import method_to_capability as method_to_capability
from .core.url import parse_uri as parse_uri
from .core.views import diagnostic_severity as diagnostic_severity, first_selection_region as first_selection_region, get_symbol_kind_from_scope as get_symbol_kind_from_scope, position_to_offset as position_to_offset, range_to_region as range_to_region, text_document_position_params as text_document_position_params, to_encoded_filename as to_encoded_filename, uri_from_view as uri_from_view
from .locationpicker import LocationPicker as LocationPicker, open_location_async as open_location_async
from _typeshed import Incomplete
from typing import TypedDict

class LspGotoCommand(LspTextCommand):
    method: str
    placeholder_text: str
    fallback_command: str
    def is_enabled(self, event: dict | None = None, point: int | None = None, side_by_side: bool = False, force_group: bool = True, fallback: bool = False, group: int = -1) -> bool: ...
    def is_visible(self, event: dict | None = None, point: int | None = None, side_by_side: bool = False, force_group: bool = True, fallback: bool = False, group: int = -1) -> bool: ...
    def run(self, _: sublime.Edit, event: dict | None = None, point: int | None = None, side_by_side: bool = False, force_group: bool = True, fallback: bool = False, group: int = -1) -> None: ...
    def _handle_response_async(self, session: Session, side_by_side: bool, force_group: bool, fallback: bool, group: int, position: int, response: None | Location | list[Location] | list[LocationLink]) -> None: ...
    def _handle_no_results(self, fallback: bool = False, side_by_side: bool = False) -> None: ...

class LspSymbolDefinitionCommand(LspGotoCommand):
    method: str
    capability: Incomplete
    placeholder_text: str
    fallback_command: str

class LspSymbolTypeDefinitionCommand(LspGotoCommand):
    method: str
    capability: Incomplete
    placeholder_text: str

class LspSymbolDeclarationCommand(LspGotoCommand):
    method: str
    capability: Incomplete
    placeholder_text: str

class LspSymbolImplementationCommand(LspGotoCommand):
    method: str
    capability: Incomplete
    placeholder_text: str

class DiagnosticData(TypedDict):
    session_name: str
    diagnostic: Diagnostic

class LspGotoDiagnosticCommand(LspWindowCommand):
    def run(self, uri: DocumentUri | None, diagnostic: DiagnosticData | None) -> None: ...
    def is_enabled(self) -> bool: ...
    def input_description(self) -> str: ...
    def input(self, args: dict) -> sublime_plugin.CommandInputHandler | None: ...
    def _has_diagnostics(self, uri: DocumentUri) -> bool: ...

class DiagnosticUriInputHandler(PreselectedListInputHandler):
    window: Incomplete
    initial_view: Incomplete
    sessions: Incomplete
    uri: Incomplete
    _preview: Incomplete
    _max_severity: Incomplete
    def __init__(self, window: sublime.Window, initial_view: sublime.View, sessions: list[Session], initial_value: DocumentUri | None = None) -> None: ...
    def name(self) -> str: ...
    def placeholder(self) -> str: ...
    def get_list_items(self) -> tuple[list[sublime.ListInputItem], int]: ...
    def preview(self, value: DocumentUri | None) -> str: ...
    def cancel(self) -> None: ...
    def confirm(self, value: DocumentUri | None) -> None: ...
    def next_input(self, args: dict) -> sublime_plugin.CommandInputHandler | None: ...
    def description(self, value: DocumentUri, text: str) -> str: ...

class DiagnosticInputHandler(sublime_plugin.ListInputHandler):
    window: Incomplete
    initial_view: Incomplete
    _preview: Incomplete
    sessions: Incomplete
    uri: Incomplete
    diagnostics: Incomplete
    def __init__(self, window: sublime.Window, initial_view: sublime.View, _preview: sublime.View | None, sessions: list[Session], uri: DocumentUri, diagnostics: list[DiagnosticData]) -> None: ...
    def name(self) -> str: ...
    def list_items(self) -> tuple[list[sublime.ListInputItem], int]: ...
    def preview(self, value: DiagnosticData | None) -> str | sublime.Html: ...
    def cancel(self) -> None: ...
    def confirm(self, value: DiagnosticData | None) -> None: ...
    def _session(self, value: DiagnosticData) -> Session | None: ...
    def _open_file(self, value: DiagnosticData, *, transient: bool = False) -> sublime.View | None: ...

def _focus_initial_view(window: sublime.Window, initial_view: sublime.View, preview: sublime.View | None) -> None: ...
