import abc
import sublime
from .core.registry import LspTextCommand as LspTextCommand
from .core.settings import userprefs as userprefs
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from typing import Any, Callable

class LspTask(ABC, metaclass=abc.ABCMeta):
    """
    Base class for tasks that run from `LspTextCommandWithTasks` command.

    Note: The whole task runs on the async thread.
    """
    @classmethod
    @abstractmethod
    def is_applicable(cls, view: sublime.View) -> bool: ...
    _task_runner: Incomplete
    _on_done: Incomplete
    _completed: bool
    _cancelled: bool
    _status_key: Incomplete
    def __init__(self, task_runner: LspTextCommand, on_done: Callable[[], None]) -> None: ...
    def run_async(self) -> None: ...
    def _on_timeout(self) -> None: ...
    def cancel(self) -> None: ...
    def _set_view_status(self, text: str) -> None: ...
    def _erase_view_status(self) -> None: ...
    def _on_complete(self) -> None: ...
    def _purge_changes_async(self) -> None: ...

class TasksRunner:
    _text_command: Incomplete
    _tasks: Incomplete
    _on_tasks_completed: Incomplete
    _pending_tasks: Incomplete
    _canceled: bool
    def __init__(self, text_command: LspTextCommand, tasks: list[type[LspTask]], on_complete: Callable[[], None]) -> None: ...
    def run(self) -> None: ...
    def cancel(self) -> None: ...
    def _process_next_task(self) -> None: ...
    def _run_next_task_async(self) -> None: ...
    def _on_task_completed_async(self) -> None: ...

class LspTextCommandWithTasks(LspTextCommand, ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def tasks(self) -> list[type[LspTask]]:
        """Returns tasks to run when command is run."""
    _tasks_runner: Incomplete
    def __init__(self, view: sublime.View) -> None: ...
    def on_before_tasks(self) -> None:
        """Override this to execute code before the task handler starts."""
    def on_tasks_completed(self, **kwargs: dict[str, Any]) -> None:
        """Override this to execute code when all tasks are completed."""
    def _on_tasks_completed(self, **kwargs: dict[str, Any]) -> None: ...
    def run(self, edit: sublime.Edit, **kwargs: dict[str, Any]) -> None: ...
