import sublime
import sublime_plugin
import weakref
from ..protocol import FileRename as FileRename, WorkspaceEdit as WorkspaceEdit
from .core.edit import show_summary_message as show_summary_message
from .core.logging import debug as debug
from .core.open import open_file_uri as open_file_uri
from .core.promise import Promise as Promise
from .core.protocol import Error as Error, Notification as Notification, Request as Request
from .core.registry import LspWindowCommand as LspWindowCommand
from .core.sessions import Session as Session
from .core.types import match_file_operation_filters as match_file_operation_filters
from .core.url import filename_to_uri as filename_to_uri
from .edit import prompt_for_workspace_edits as prompt_for_workspace_edits
from _typeshed import Incomplete
from collections.abc import Generator
from typing import Any, TypedDict
from typing_extensions import NotRequired

class RenamePathInputHandler(sublime_plugin.TextInputHandler):
    path: Incomplete
    def __init__(self, path: str) -> None: ...
    def name(self) -> str: ...
    def placeholder(self) -> str: ...
    def initial_text(self) -> str: ...
    def initial_selection(self) -> list[tuple[int, int]]: ...
    def validate(self, path: str) -> bool: ...

class LspRenamePathInputArgs(TypedDict):
    paths: NotRequired[list[str]]
    new_name: NotRequired[str]
    prompt_workspace_edits: NotRequired[bool]

class LspRenamePathCommand(LspWindowCommand):
    capability: str
    @staticmethod
    def is_case_change(path_a: str, path_b: str) -> bool: ...
    def is_visible(self, **kwargs: dict[str, Any]) -> bool: ...
    def want_event(self) -> bool: ...
    def input(self, args: LspRenamePathInputArgs) -> sublime_plugin.TextInputHandler | None: ...
    def run(self, new_name: str, paths: list[str] | None = None, prompt_workspace_edits: bool = True) -> None: ...
    def on_rename_path(self, success: bool, file_rename: FileRename) -> None: ...
    def prompt_rename_async(self, file_rename: FileRename, label: str, rename_command_args: dict[str, Any]) -> None: ...
    def create_will_rename_requests_async(self, file_rename: FileRename) -> Generator[Promise[tuple[WorkspaceEdit | None | Error, weakref.ref[Session]]]]: ...
    def return_response_with_session(self, weak_session: weakref.ref[Session], response: WorkspaceEdit | None | Error) -> tuple[WorkspaceEdit | None | Error, weakref.ref[Session]]: ...
    def handle_rename_async(self, responses: list[tuple[WorkspaceEdit | None | Error, weakref.ref[Session]]], label: str, rename_command_args: dict[str, Any]) -> None: ...
    def on_prompt_for_workspace_edits_concluded(self, weak_session: weakref.ref[Session], response: WorkspaceEdit, label: str, accepted: bool) -> Promise[bool]: ...
    def rename_path(self, old: str, new: str) -> Promise[bool]: ...
    def notify_did_rename(self, file_rename: FileRename) -> None: ...
    def restore_view(self, selection: list[sublime.Region], group: tuple[int, int], view: sublime.View | None) -> None: ...
    def focus_view(self, path: str | None) -> None: ...
