import sublime
import sublime_plugin
import weakref
from ..protocol import PrepareRenameParams as PrepareRenameParams, PrepareRenameResult as PrepareRenameResult, Range as Range, RenameParams as RenameParams, WorkspaceEdit as WorkspaceEdit
from .core.edit import show_summary_message as show_summary_message
from .core.protocol import Request as Request
from .core.registry import LspTextCommand as LspTextCommand, get_position as get_position
from .core.sessions import Session as Session
from .core.views import range_to_region as range_to_region, text_document_position_params as text_document_position_params
from .edit import prompt_for_workspace_edits as prompt_for_workspace_edits
from _typeshed import Incomplete
from typing import Any
from typing_extensions import TypeGuard

PREPARE_RENAME_CAPABILITY: str

def is_range_response(result: PrepareRenameResult) -> TypeGuard[Range]: ...

class LspSymbolRenameCommand(LspTextCommand):
    capability: str
    def is_visible(self, new_name: str = '', placeholder: str = '', session_name: str | None = None, event: dict | None = None, point: int | None = None) -> bool: ...
    def input(self, args: dict) -> sublime_plugin.TextInputHandler | None: ...
    def run(self, edit: sublime.Edit, new_name: str = '', placeholder: str = '', session_name: str | None = None, event: dict | None = None, point: int | None = None) -> None: ...
    def _get_prepare_rename_session(self, point: int | None, session_name: str | None) -> Session | None: ...
    def _do_rename(self, position: int, old_name: str, new_name: str, preferred_session: Session | None) -> None: ...
    def _on_rename_result_async(self, session: Session, label: str, response: WorkspaceEdit | None) -> None: ...
    def on_prompt_for_workspace_edits_concluded(self, weak_session: weakref.ref[Session], response: WorkspaceEdit, accepted: bool) -> None: ...
    def _on_prepare_result(self, pos: int, session_name: str | None, response: PrepareRenameResult | None) -> None: ...
    def _on_prepare_error(self, error: Any) -> None: ...

class RenameSymbolInputHandler(sublime_plugin.TextInputHandler):
    def want_event(self) -> bool: ...
    view: Incomplete
    _placeholder: Incomplete
    def __init__(self, view: sublime.View, placeholder: str) -> None: ...
    def name(self) -> str: ...
    def placeholder(self) -> str: ...
    def initial_text(self) -> str: ...
    def validate(self, name: str) -> bool: ...
