import sublime
from .core.registry import LspTextCommand as LspTextCommand
from typing import Any, Callable

SemanticTokensInfo = tuple[str, str, str]
POPUP_CSS: str

def copy(view: sublime.View, text: str) -> None: ...

class LspShowScopeNameCommand(LspTextCommand):
    """
    Like the builtin show_scope_name command from Default/show_scope_name.py,
    but will also show semantic tokens if applicable.
    """
    capability: str
    def want_event(self) -> bool: ...
    def run(self, _: sublime.Edit) -> None: ...
    def _get_semantic_info(self, point: int) -> SemanticTokensInfo | None: ...
    def _render_with_plain_string_stackframes(self, scope: str, scope_list: str, stack: list[str], semantic_info: SemanticTokensInfo | None) -> None: ...
    def _render_with_fancy_stackframes(self, scope: str, scope_list: str, stack: list[Any], semantic_info: SemanticTokensInfo | None) -> None: ...
    def _show_popup(self, digits_len: int, scope: str, scope_list: str, backtrace: str, semantic_info: SemanticTokensInfo | None, on_navigate: Callable[[str], None]) -> None: ...
    def on_navigate(self, link: str) -> None: ...
