name: Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ruff:
    runs-on: ubuntu-latest

    env:
      UV_SYSTEM_PYTHON: 1

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install -U uv
          make install-dev

      - name: Lint
        run: |
          make ci-check
