name: Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - uses: astral-sh/ruff-action@v3
        with:
          version-file: 'requirements-dev.txt'
      - run: ruff check
      - run: ruff format --diff
