name: Check/update settings schema

on:
  pull_request:
    branches:
      - main
    paths:
      - 'language-server/package.json'

jobs:
  check-settings:
    uses: sublimelsp/workflows/.github/workflows/changed-settings.yaml@v2
    with:
      version_file: 'language-server/package.json'
      version_regexp: '"bash-language-server": "(\d+\.\d+\.\d+)"'
      version_transform: 'server-{}'
